# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: gianasista blog
email: mail@gianasista.de
description: > # this means to ignore newlines until "baseurl:"
  This is my blog about all the technical stuff I do in my free time. It is meant as some kind of documentation for me.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.gianasista.de" # the base hostname & protocol for your site
twitter_username: gianasista
github_username:  gianasista

# Build settings
markdown: kramdown
